export const products = [
  {
    slug: "rh-4592",
    title: "Tandem Box Drawer Slide – Soft Close (500mm)",
    brand: "Ebco",
    category: "Furniture Fittings",
    sku: "RH-4592",
    image: "/prodimg/tandembox500.png",
    description: "Premium stainless steel drawer slide featuring silent soft-close technology.",
    minOrder: "12 Pairs",
    stockStatus: "In Stock",
  },
  {
    slug: "pidilite-swr-plus",
    title: "Fevicol SWR Plus Adhesive",
    brand: "Pidilite",
    category: "Adhesives",
    sku: "PL-SWR-PLUS",
    image: "/prodimg/swrplusd3.png",
    description: "High strength synthetic resin adhesive suitable for woodworking and general applications.",
    minOrder: "50 kg",
    stockStatus: "In Stock",
  },
  {
    slug: "rh-gs-100",
    title: "Hydraulic Gas Spring Lift Support",
    brand: "Ebco",
    category: "Furniture Fittings",
    sku: "RH-GS-100",
    image: "/prodimg/hydraulicgasspring.png",
    description: "Heavy-duty 100N gas spring for overhead cabinet doors.",
    minOrder: "20 Pieces",
    stockStatus: "Limited Stock",
  },
  {
    slug: "soft-close-hinge",
    title: "Soft Close Clip-On Cabinet Hinge",
    brand: "Ebco",
    category: "Furniture Fittings",
    sku: "RH-HG-110",
    image: "/prodimg/softclose.png",
    description: "Hydraulic hinge system designed for silent cabinet door closing.",
    minOrder: "100 Pieces",
    stockStatus: "In Stock",
  },
  {
    slug: "bb-slide-400",
    title: "Ball Bearing Drawer Slide 400mm",
    brand: "Ebco",
    category: "Sliding Systems",
    sku: "RH-BB-400",
    image: "/prodimg/ballbearing400.png",
    description: "Heavy duty ball bearing drawer slide for kitchen drawers.",
    minOrder: "20 Pairs",
    stockStatus: "In Stock",
  },
  {
    slug: "bb-slide-450",
    title: "Ball Bearing Drawer Slide 450mm",
    brand: "Ebco",
    category: "Sliding Systems",
    sku: "RH-BB-450",
    image: "/prodimg/ballbearing450.png",
    description: "Smooth sliding mechanism with corrosion resistant coating.",
    minOrder: "20 Pairs",
    stockStatus: "In Stock",
  },
  {
    slug: "kitchen-basket",
    title: "Stainless Steel Kitchen Basket",
    brand: "Ebco",
    category: "Kitchen Accessories",
    sku: "RH-KB-001",
    image: "/prodimg/sskitchenbasket.png",
    description: "Premium 304 stainless steel kitchen basket for modular kitchens.",
    minOrder: "15 Pieces",
    stockStatus: "In Stock",
  },
  {
    slug: "cutlery-tray",
    title: "Modular Kitchen Cutlery Tray",
    brand: "Ebco",
    category: "Kitchen Accessories",
    sku: "RH-CT-002",
    image: "/prodimg/cutlerytray.png",
    description: "Durable plastic cutlery organizer for kitchen drawers.",
    minOrder: "5 Pieces",
    stockStatus: "In Stock",
  },
  {
    slug: "corner-carousel",
    title: "Kitchen Corner Carousel",
    brand: "Ebco",
    category: "Kitchen Accessories",
    sku: "RH-CC-100",
    image: "/prodimg/cornercarousel.png",
    description: "360° rotating storage system for corner cabinets.",
    minOrder: "1 Piece",
    stockStatus: "In Stock",
  },
  {
    slug: "pidilite-probond",
    title: "Fevicol Probond Adhesive",
    brand: "Pidilite",
    category: "Adhesives",
    sku: "PB-200",
    image: "/prodimg/probond.png",
    description: "Professional bonding adhesive for industrial woodworking.",
    minOrder: "10 Kg",
    stockStatus: "In Stock",
  },
  {
    slug: "jowat-280-30",
    title: "Jowat 280.30 Edge Banding Adhesive",
    brand: "Jowat",
    category: "Adhesives",
    sku: "JW-28030",
    image: "/prodimg/jowat28030.png",
    description: "Hotmelt adhesive designed for edge banding applications.",
    minOrder: "25 kg",
    stockStatus: "In Stock",
  },
  {
    slug: "jowat-280-50",
    title: "Jowat 280.50 Hotmelt Adhesive",
    brand: "Jowat",
    category: "Adhesives",
    sku: "JW-28050",
    image: "/prodimg/jowat28050.png",
    description: "Industrial hotmelt adhesive for wood panel bonding.",
    minOrder: "25 kg",
    stockStatus: "In Stock",
  },
  {
    slug: "jowat-284-70",
    title: "Jowat 284.70 Adhesive",
    brand: "Jowat",
    category: "Adhesives",
    sku: "JW-28470",
    image: "/prodimg/jowat28470.png",
    description: "High performance adhesive for furniture manufacturing.",
    minOrder: "25 kg",
    stockStatus: "In Stock",
  },
  {
    slug: "jowat-288-60",
    title: "Jowat 288.60 Adhesive",
    brand: "Jowat",
    category: "Adhesives",
    sku: "JW-28860",
    image: "/prodimg/jowat28860.png",
    description: "Industrial grade bonding adhesive for panel processing.",
    minOrder: "25 kg",
    stockStatus: "In Stock",
  },
  {
    slug: "wd40-multi",
    title: "WD-40 Multi-Use Lubricant",
    brand: "WD-40",
    category: "Lubricants",
    sku: "WD40-001",
    image: "/prodimg/wd40.png",
    description: "Multi-purpose lubricant for rust protection and maintenance.",
    minOrder: "24 Cans",
    stockStatus: "In Stock",
  },
  {
  slug: "pidilite-hotmelt",
  title: "Fevicol Hotmelt Adhesive (MNL Transparent)",
  brand: "Pidilite",
  category: "Adhesives",
  sku: "PL-HM-MNL",
  image: "/prodimg/hotmelt.png",
  description: "Transparent hotmelt adhesive suitable for edge banding and woodworking applications.",
  minOrder: "30 kg",
  stockStatus: "In Stock",
  },
  {
  slug: "woodlok-ag88",
  title: "Woodlok AG88 Adhesive",
  brand: "Pidilite",
  category: "Adhesives",
  sku: "PL-WL-AG88",
  image: "/prodimg/woodlok.png", 
  description: "Marine-grade waterproof adhesive designed for high moisture resistance.",
  minOrder: "50kg",
  stockStatus: "In Stock",
  },
];